"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

sequence = [1,2]

while True:
    
    num = sequence[-1] + sequence[-2]

    if num < 4_000_000:
      sequence.append(num)
    
    else:
       break

total_sum = 0

for i in sequence:
   if i % 2 == 0:
      total_sum += i

print("answer: ", total_sum)  


