"""

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

"""






def triangle_numbers(x,y, tn_list):
  while x < y+1:

    triangle_number = sum(i for i in range(1,x+1))
    tn_list.append(triangle_number)
    x += 1



x = 1
y = 5
z = 0 

a = True

while a:
  
  tn_list = []

  triangle_numbers(x,y, tn_list)

  for i in tn_list:
    divisors = []

    for j in range(1,int(i**0.5) + 1):
      if i % j == 0:
        divisors.append(int(i / j))
    

    if len(divisors) > 250:
      print("FOUND:", i)
      a = False
      break

    if a == False:
      break
   
  if a == True:
    x += 5
    y += 5
