"""

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""

triangle_numbers = [int((number/2)*(number+1)) for number in range(1,100000)]
pentagonal_numbers = [int(number*(3*number-1)/2) for number in range(1,100000)]
hexagonal_numbers = [int(number*(2*number-1)) for number in range(1,100000)]


all_numbers = []

for num in triangle_numbers:
    if num in pentagonal_numbers and num in hexagonal_numbers:
      all_numbers.append(num)

print(all_numbers)